import os
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

OUTPUT_DIR = 'outputs/charts'
os.makedirs(OUTPUT_DIR, exist_ok=True)

def df_to_figure(df, title=None, figsize=(11,6), max_rows=20):
    fig, ax = plt.subplots(figsize=figsize)
    ax.axis('off')
    if title:
        ax.set_title(title, fontsize=14)
    # trim df
    display_df = df.copy()
    if display_df.shape[0] > max_rows:
        display_df = display_df.head(max_rows)
    table = ax.table(cellText=display_df.values, colLabels=display_df.columns, loc='center')
    table.auto_set_font_size(False)
    table.set_fontsize(8)
    table.scale(1, 1.2)
    return fig

def main():
    scorecard_path = 'fund_scorecard.csv'
    alpha_path = 'data/processed/alpha_beta.csv'
    returns_summary = 'returns_summary.csv'
    bench_png = os.path.join(OUTPUT_DIR, 'benchmark_comparison.png')
    hist_png = os.path.join(OUTPUT_DIR, 'daily_returns_histograms.png')

    score = pd.read_csv(scorecard_path)
    alpha = pd.read_csv(alpha_path)
    ret_sum = pd.read_csv(returns_summary)

    out_pdf = os.path.join(OUTPUT_DIR, 'Performance_Report.pdf')
    with PdfPages(out_pdf) as pdf:
        # cover
        fig, ax = plt.subplots(figsize=(11,8.5))
        ax.axis('off')
        ax.text(0.5, 0.6, 'Mutual Fund Performance Report', ha='center', va='center', fontsize=24)
        ax.text(0.5, 0.45, 'Generated by compute_metrics.py', ha='center', va='center', fontsize=10)
        pdf.savefig(fig)
        plt.close(fig)

        # Top 10 scorecard
        top10 = score[['amfi_code','scheme_name','fund_score','cagr_3y','sharpe','max_drawdown']].head(10)
        fig = df_to_figure(top10, title='Top 10 Funds by Score')
        pdf.savefig(fig)
        plt.close(fig)

        # Alpha/Beta top 10
        ab = alpha.reset_index()
        fig = df_to_figure(ab.head(10), title='Alpha/Beta (top rows)')
        pdf.savefig(fig)
        plt.close(fig)

        # Returns summary (first 20)
        fig = df_to_figure(ret_sum.head(20), title='Returns Summary (sample)')
        pdf.savefig(fig)
        plt.close(fig)

        # Charts
        if os.path.exists(bench_png):
            fig = plt.figure(figsize=(11,8.5))
            img = plt.imread(bench_png)
            plt.imshow(img)
            plt.axis('off')
            pdf.savefig(fig)
            plt.close(fig)

        if os.path.exists(hist_png):
            fig = plt.figure(figsize=(11,8.5))
            img = plt.imread(hist_png)
            plt.imshow(img)
            plt.axis('off')
            pdf.savefig(fig)
            plt.close(fig)

    print('Saved PDF:', out_pdf)

if __name__ == '__main__':
    main()
